Assignment: Database-Driven Product Server, Part 2
alexhcole95/pivottechschool pull request #10
Opened 2022-11-25 01:18 UTC by alexhcole95

## Summary

Completed the second part of the database-driven product server assignment, which was refactoring http handlers.

## Changes

1. Updated README file to include the assignment instructions.
2. Created and implemented proper HTTP handlers in main.go.
3. Modified and tidied directories.

## Output

### GET

<img width="530" alt="Screen Shot 2022-11-24 at 7 04 04 PM" src="https://user-images.githubusercontent.com/105764114/203881389-e56aa6be-7008-4c62-b170-28d8af4b7b9e.png">
<img width="875" alt="Screen Shot 2022-11-24 at 7 09 36 PM" src="https://user-images.githubusercontent.com/105764114/203881409-79534708-2e97-4b32-bd3e-b43aa6ea4c59.png">

### POST

<img width="563" alt="Screen Shot 2022-11-24 at 7 06 32 PM" src="https://user-images.githubusercontent.com/105764114/203881463-efca1e66-93a4-46fb-89ee-08fb0fab1c46.png">
<img width="858" alt="Screen Shot 2022-11-24 at 7 06 02 PM" src="https://user-images.githubusercontent.com/105764114/203881474-d957d5b6-3973-48fa-ba1e-77d5cde789df.png">

### PUT

<img width="584" alt="Screen Shot 2022-11-24 at 7 07 29 PM" src="https://user-images.githubusercontent.com/105764114/203881544-400f41ce-1ae7-4006-bd37-8e906ce8306a.png">
<img width="856" alt="Screen Shot 2022-11-24 at 7 07 15 PM" src="https://user-images.githubusercontent.com/105764114/203881555-c29c4fad-85ac-4a33-bd6a-1122028a94b7.png">

### DELETE

<img width="601" alt="Screen Shot 2022-11-24 at 7 08 30 PM" src="https://user-images.githubusercontent.com/105764114/203881571-6aed18be-de73-4b82-8ad8-f379f6cefdac.png">
<img width="832" alt="Screen Shot 2022-11-24 at 7 08 18 PM" src="https://user-images.githubusercontent.com/105764114/203881580-87c88f1d-829a-4f20-90b4-5cc1d95e9275.png">

2022-11-25 17:03 UTC, alexhcole95 commented
I am having issues with the first GET instruction which is:

`GET /products?limit=<numeric>&sort=<column>`

As you can see from my code (line 59 - 79), I feel like I have an idea of what to do, however it's not working for me. I believe my problem lies with understanding how a request works past the `?limit=<num>&...` part as this is the first time I've worked with that. I've spend a good bit of time on Google and haven't found the appropriate resource yet. Can you point me in the right direction?

2022-11-27 20:58 UTC, jboursiquot requested changes
Changes needed.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +		products = append(products, product{ID: id, Name: name, Price: price})
No. You don't want to load up an entire database table worth of products into memory. Query the database as needed.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	if lim < 0 || lim > int64(len(products)) {
No. Remove the use of `products` from your handlers.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +		if _, err = db.Exec("SELECT * FROM products WHERE id = ? LIMIT ?", sort, lim); err != nil {
`sort` will be assigned to `id` here. Not what you want.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	if itemID < 0 || itemID > int64(len(products)) {
Remove use of `products` here.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +		for _, product := range products {
No. Query the database for the product you need.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	items = append(products, item)
No use of `products`.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	if item.Name == "" || item.ID == 0 || item.Price == 0 {
Maybe put all of these validations behind a single method?

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +		for i, product := range products {
Remove use of `products`.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +					log.Fatal(err)
Don't crash your own server if a query fails.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	if itemID < 0 || itemID > int64(len(products)) {
Remove use of `products`.

2022-11-27 20:58 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +			log.Fatal(err)
Don't crash your own server.

2022-12-03 20:17 UTC, jboursiquot requested changes

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +var info []product
No need to have this as a global.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +		info = append(info, product{ID: id, Name: name, Price: price})
Just create a local `products` var to hold your products and return that. No need to use the global here.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	rows, err := db.Query("SELECT * FROM products")
Simplify this handler by using the `QueryRow` method instead.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	} else {
No need for an `else` cause here. return early if there's an error.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	items = append(info, item)
Why the need for this `items`?

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	rows, err := db.Query("SELECT * FROM products")
Simplify with `QueryRow` method.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	if updatedProduct.Name == "" || updatedProduct.ID == 0 || updatedProduct.Price == 0 {
Put all of this validation behind a `validate() error` method on `Product`.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	} else {
No need for `else`. Return early.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +		for i, product := range info {
You're not going to need to use any loops here if you use `QueryRow`.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +	} else {
Use early return. No `else` needed.

2022-12-03 20:17 UTC, jboursiquot commented on cmd/database-driven-server/main.go
> +		info = newProduct
Why are you doing this here?

2022-12-31 21:26 UTC, closed without merging