Assignment: Writing Tests
alexhcole95/pivottechschool pull request #5
Opened 2022-11-04 00:32 UTC by alexhcole95

## Summary

Completed writing tests assignment with working calculator and applicable testing file.

## Changes

1. Completed assignment.
2. Created calculator directory with calculator.go and calculator_test.go files.
3. Created main.go file for calculator usage.

2022-11-04 14:38 UTC, jboursiquot requested changes
Good start. In addition to the inline comments, do the following:

- Put your `main.go` in a `cmd/calculator` folder. Follow the convention for executables in Go.
- You should rename your readme.md to README.md. Again, a convention that reduces the cognitive load on everybody.

2022-11-04 14:38 UTC, jboursiquot commented on calculator/calculator_test.go
> +	result := calculator.Add(1, 2)
Use the table-driven testing technique.

2022-11-04 14:38 UTC, jboursiquot commented on calculator/calculator_test.go
> +	result, err := calculator.Divide(6, 3)
You need to also test the divide-by-zero case. Do so within a table-driven setup.

2022-11-04 14:38 UTC, jboursiquot commented on calculator/calculator_test.go
> +	result := calculator.Multiply(5, 3)
Make table-driven.

2022-11-04 14:38 UTC, jboursiquot commented on main.go
> +func main() {
You're doing a lot more than asked for by the assignment.

It's okay because you're learning and you're doing so in class but as a professional, you want to solve the problem you have, no more, no less. Any additional effort needs to be a proposal to your team that has buy-in before you proceed with the actual work. This is because code maintenance has a cost. Any unnecessary code you add to a project or codebase adds to that cost.

2022-11-10 16:47 UTC, alexhcole95 commented on calculator/calculator_test.go
> +	result := calculator.Add(1, 2)
Hey Johnny, 

Aside from renaming the readme.md to README.md, removing the HTML tags, and moving the main.go file I believe I did a table-driven testing technique. I did some Googling and found some stuff on my own (along with your video) and think I may have got it. Let me know if that looks right though. I appreciate your feedback and patience!

2022-11-13 00:24 UTC, jboursiquot approved these changes
Nice work.

2022-11-14 22:24 UTC, closed without merging