Assignment: Product Server
alexhcole95/pivottechschool pull request #6
Opened 2022-11-04 01:01 UTC by alexhcole95

## Summary

Completed product server assignment with working HTTP methods and tested with Insomnia.

## Changes

1. Completed assignment.
2. Deleted/tidied some files.
3. Moved some directories.

2022-11-04 14:51 UTC, jboursiquot requested changes
Good work. Address the feedback and resubmit.

2022-11-10 02:47 UTC, alexhcole95 commented on server/main.go
> +	products = append(products, item)
Hey Johnny, I am resubmitting all of these reviews, but unfortunately I am having trouble understanding what is occurring here. When I test this in Insomnia, I can type in the new ID and it applies the ID typed and not 0.

2022-11-13 00:30 UTC, jboursiquot requested changes

2022-11-13 00:30 UTC, jboursiquot commented on server/main.go
> +	reqBody, _ := ioutil.ReadAll(r.Body)
You're discarding this error. Handle it.

2022-11-13 00:30 UTC, jboursiquot commented on server/main.go
> +	products = append(products, item)
This means you're submitting the payload with an `id` already set. Yes?

2022-11-13 00:30 UTC, jboursiquot commented on server/main.go
> +	reqBody, _ := ioutil.ReadAll(r.Body)
Do not discard this error. Handle it.

2022-11-13 00:30 UTC, jboursiquot commented on server/main.go
> +		if int64(product.ID) == id {
Once you've found and updated the product, there's no need to keep iterating. Break out of the loop.

2022-11-14 22:51 UTC, alexhcole95 commented on server/main.go
> +	products = append(products, item)
That's right, in Insomnia I am typing in the ID when I create a payload.

2022-11-18 20:23 UTC, jboursiquot requested changes

2022-11-18 20:23 UTC, jboursiquot commented on cmd/server/go.mod
> +module pivottechschool
Avoid modules in your executable's folder. You only need a single go.mod file at the root of your repo.

2022-11-18 20:23 UTC, jboursiquot commented on cmd/server/main.go
> +		http.Error(w, "Unable to convert string to int", http.StatusInternalServerError)
Return a 400 Bad Request to indicate to the caller that the `id` is not valid. This is not an internal server error but a client error.

2022-11-18 20:23 UTC, jboursiquot commented on cmd/server/main.go
> +		http.Error(w, "Unable to read request body", http.StatusInternalServerError)
Return a 400 Bad Request to indicate to the caller that the id is not valid. This is not an internal server error but a client error.

2022-11-18 20:23 UTC, jboursiquot commented on cmd/server/main.go
> +	products = append(products, item)
How does your product's ID get set? The client should not be the one to pass it in if that's what's happening.

2022-11-18 20:23 UTC, jboursiquot commented on cmd/server/main.go
> +		http.Error(w, "Unable to convert string to int", http.StatusInternalServerError)
Return a 400 Bad Request to indicate to the caller that the id is not valid. This is not an internal server error but a client error.

2022-11-18 20:23 UTC, jboursiquot commented on cmd/server/main.go
> +		http.Error(w, "Unable to convert string to int", http.StatusInternalServerError)
Return a 400 Bad Request to indicate to the caller that the id is not valid. This is not an internal server error but a client error.

2022-11-18 20:23 UTC, jboursiquot commented on cmd/server/main.go
> +	for _, product := range products {
You're not deleting any product here.

2022-11-24 23:39 UTC, jboursiquot approved these changes

2022-11-24 23:40 UTC, jboursiquot commented
You'll need to resolve your conflicts before merging.

2022-11-25 01:27 UTC, merged